services:
  app:
    image: troddit
    build:
      dockerfile: Dockerfile
    expose:
      - 3000 
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx:
    external: true
    name: nginx
